[run]
init_cmds = [
	["make"],
	["./switch"]
]
watch_all = true
watch_dirs = [
	"$WORKDIR/models",
	"$WORKDIR/modules",
	"$WORKDIR/routers"
]
watch_exts = [".go", ".ini"]
build_delay = 1500
cmds = [
	["make"],
	["./switch"]
]